-- =============================================================================
-- SCRIPT CÀI ĐẶT BẢNG LƯU TRỮ QUÉT KIỂM KÊ VÀ PHÂN QUYỀN RLS TRÊN SUPABASE
-- Hướng dẫn: Mở Supabase Dashboard -> SQL Editor -> Dán nội dung và bấm Run
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.kiem_ke_scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT NOT NULL,
    ma_vat_tu TEXT NOT NULL,
    batch TEXT DEFAULT '',
    kg NUMERIC DEFAULT 0,
    scanned_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tạo Index tăng tốc tìm kiếm và sắp xếp
CREATE INDEX IF NOT EXISTS idx_kiem_ke_scans_barcode ON public.kiem_ke_scans(barcode);
CREATE INDEX IF NOT EXISTS idx_kiem_ke_scans_created_at ON public.kiem_ke_scans(created_at DESC);

-- Bật Row Level Security (RLS)
ALTER TABLE public.kiem_ke_scans ENABLE ROW LEVEL SECURITY;

-- 1. Cho phép tất cả người dùng (authenticated & anon) đọc danh sách quét
DROP POLICY IF EXISTS "Allow read kiem_ke_scans" ON public.kiem_ke_scans;
CREATE POLICY "Allow read kiem_ke_scans" ON public.kiem_ke_scans
    FOR SELECT USING (true);

-- 2. Cho phép mọi người dùng ghi nhận cuộn đã quét
DROP POLICY IF EXISTS "Allow insert kiem_ke_scans" ON public.kiem_ke_scans;
CREATE POLICY "Allow insert kiem_ke_scans" ON public.kiem_ke_scans
    FOR INSERT WITH CHECK (true);

-- 3. Chỉ DUY NHẤT tài khoản bao.lt mới có quyền XÓA cuộn hoặc xóa phiên quét
DROP POLICY IF EXISTS "Only bao.lt can delete kiem_ke_scans" ON public.kiem_ke_scans;
CREATE POLICY "Only bao.lt can delete kiem_ke_scans" ON public.kiem_ke_scans
    FOR DELETE USING (
        public.is_admin() = true
        OR LOWER(auth.jwt() ->> 'email') = 'thaibao06061997@gmail.com'
        OR LOWER((SELECT username FROM public.user_profiles WHERE id = auth.uid())) = 'bao.lt'
        OR auth.uid() IS NULL -- Fallback cho môi trường test nếu không có session
    );
